server:
  port: 8080
spring:
  data:
    mongodb:
      host: 127.0.0.1
      dynamic:
        config:
          test-1:
            host: 127.0.0.1
          test-2:
            host: 127.0.0.1
logging:
  level:
    root: info
    com.opensource.cuukenn.dynamic.database.mongodb: debug
